Merge Frontend to Main branch
aegisnull/news-explorer-frontend pull request #1
Opened 2022-12-27 06:21 UTC by aegisnull

Hola equipo,

He creado esta PR para integrar los cambios que he realizado en la rama `stage-react-api`. En concreto, he terminado el desarrollo del frontend para la aplicación de News Explorer.

El diseño responsivo está listo así como la conexión directa con la API de `NewsApi`, las ventanas modales también son funcionales.

Se siguió la recomendación de no utilizar componentes de clase, el desarrollo fue realizado en un entorno de desarrollo con `NodeJS en su versión 18.12.1`

Espero que estos cambios sean útiles y me gustaría solicitar una revisión antes de fusionarlos con el código principal.

Gracias,
_- Luis Tellez | MERN Full Stack Web Developer_

2022-12-27 14:12 UTC, Educg550 requested changes
Marcación JSX: 74.6
Buenas prácticas: 12.86
Recomendaciones: 3.34

Auth con React: 23.6 (se causa un error al intentar hacer login como usuario, además la ruta que debería estar protegida muestra que el nombre del usuario actual és "Elise", aunque no se haya hecho Login. También hace falta implementar la funcionalidad de tu token de autenticación)
Componentes con React: 17.64 (la funcionalidad de contexto de tu usuario no se ha creado, aunque tengas el contexto de noticias creado. El contexto no se aplica dentro de tu App.js)
Buenas prácticas: 7.5 (las requisiciones a tu API se hacen en Main, no en App.js)
Recomendaciones: 5

Media total: 144.64 / 2 = 72.32

Verifica los comentarios marcados para que se apruebe tu proyecto. Ten en cuenta que tu proyecto será aprobado cuando todas las observaciones marcadas como "Necesita corrección" sean solucionadas. Una vez hecho esto, su trabajo será aprobado y podrá continuar con su aprendizaje. Aparte de eso, espero haber cubierto casi todo en tu proyecto, ¡te deseo éxito y buena suerte en tus estudios!

2022-12-27 14:12 UTC, Educg550 commented on public/index.html
> +<html lang="es">
Configuraste bien los metadatos de tu página.

2022-12-27 14:12 UTC, Educg550 commented on src/components/PopupWithForm/SignInPopup.js
> +    props.onSignIn();
Verifica si esa función és pasada en los parámetros de tu componente correctamente, parece no estar definida, algo que impide que tu página haga Login de los usuarios.

2022-12-27 14:12 UTC, Educg550 commented on src/components/Header/Header.scss
> +    &__nav {
No dejes clases vacías dentro de tu CSS

2022-12-27 14:12 UTC, Educg550 commented on src/components/Header/Header.scss
> +    &__logo {
No dejes clases vacías dentro de tu CSS

2022-12-27 14:12 UTC, Educg550 commented on src/App.js
> +          path="/saved-news"
Esta ruta no está protegida contra usuarios no autenticados

2022-12-27 14:12 UTC, Educg550 commented on src/utils/NewsApi.js
> +function getNews(keyword) {
Tu función principal de API no és asíncrona

2022-12-29 08:33 UTC, aegisnull commented
Solucionados todos los problemas encontrados durante la revisión.

Asimismo se ha implementado Autenticación con React, de momento esta es a través de la API de Practicum https://register.nomoreparties.co sin embargo una vez implementado el backend, estas llamadas serán desde el servidor propio.

2022-12-29 22:38 UTC, Educg550 approved these changes
Markup y JSX: 80 (mejor puntuación, enhorabuena!)
Mejores prácticas: 15 (mejor puntuación, enhorabuena!)
Recomendaciones: 3.33 (mejor puntuación, enhorabuena!)
Autorización y solicitudes con React: 22.04 (¡bien hecho, cumplió con todas las mejores prácticas!)

Puntuación Total: 98.33 (Aprobado, ¡muy bien hecho!) Demostraste buenas prácticas en tu código y buenos hábitos de estandarización en tu desarrollo, además de haber mostrado domínio con la estilización y diseño de tu página, está bien proyectada y sigue la metodología BEM, ¡felicidades! ¡Te deseo éxito y éxito en tu carrera como desarrollador!

2022-12-30 02:20 UTC, merged